crud/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("delete/<int:todo_pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),

]

crud/todospjt/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls')),
]

crud/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    content = models.CharField(max_length = 80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add = True)
    deadline = models.DateField(null = True)

crud/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
# Create your views here.

def index(request):

    todos = Todo.objects.all()
    todos = todos.order_by('priority')
    context = {
        'todos':todos
    }


    return render(request, 'todos/index.html',context)

def create(request):
    # 할 일 만든거
    content = request.GET.get("content")
    priority = request.GET.get("priority")
    deadline = request.GET.get("deadline")
    Todo.objects.create(content=content,priority=priority,deadline=deadline)

    return redirect('todos:index')

def delete(request,todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.delete()
    
    return redirect("todos:index")

def update(request,pk):

    todo = Todo.objects.get(pk=pk)
    print(todo)

    if todo.completed == 0:
        todo.completed = 1
        

    elif todo.completed == 1:
        todo.completed = 0
    todo.save()

    print(todo.completed)
    return redirect("todos:index")

crud/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">

    <style>
        * {
            font-family: 'Noto Sans KR', sans-serif;
        }
    </style>
</head>

<body>
    {% block content %}
    {% endblock %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

crud/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">

    <h1 class="text-center mb-3">이 곳은 To Do List</h1>

    <form action="{% url 'todos:create' %}">
        <!-- 할 일 입력 -->
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">할 일</span>
            <input type="text" name="content" maxlength="10" class="form-control" aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-default">
        </div>
        <!-- 우선 순위 -->
        <div class="input-group mb-3">
            <label class="input-group-text" for="inputGroupSelect01">우선 순위</label>
            <select class="form-select" id="inputGroupSelect01" name="priority">
                <option value="1">1</option>
                <option value="2">2</option>
                <option selected value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <!-- 달력 -->
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">마감 기한</span>
            <input type="date" name="deadline" value="2022-09-29" min="2022-09-29" max="2025-01-01" class="form-control"
                aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
        </div>


        <!-- 제출 버튼 -->
        <div class="d-grid gap-2">
            <input class="btn btn-primary" type="submit" , value="할 일 추가">
        </div>
    </form>
    <hr>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">우선순위</th>
                <th scope="col">할 일</th>
                <th scope="col">생성 날짜</th>
                <th scope="col">마감 기한</th>
                <th scope="col">진행 상태</th>
                <th scope="col">상태 변경</th>
                <th scope="col">삭제</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for todo in todos %}
            <tr class=" align-middle">
                <!-- 우선 순위 -->
                <th class="text-center" scope="row">{{ todo.priority }}</th>
                {% if todo.completed == 1 %}
                <td class="text-decoration-line-through">{{ todo.content }}</td>
                {% else %}
                <td>{{ todo.content }}</td>
                {% endif %}
                {% if todo.completed == 1 %}
                <td class="text-center text-decoration-line-through">
                    {{ todo.created_at.year }}-{{ todo.created_at.month }}-{{ todo.created_at.day }}

                </td>
                {% else %}
                <td class="text-center">{{ todo.created_at.year }}-{{ todo.created_at.month }}-{{ todo.created_at.day }}
                </td>
                {% endif %}

                {% if todo.completed == 1 %}
                <td class="text-center text-decoration-line-through">
                    {{ todo.deadline.year }}-{{ todo.deadline.month }}-{{ todo.deadline.day }}</td>
                {% else %}
                <td class="text-center">{{ todo.deadline.year }}-{{ todo.deadline.month }}-{{ todo.deadline.day }}</td>
                {% endif %}



                <!-- 진행 상태 -->
                <td class="text-center">{{ todo.completed }}</td>
                <!-- 상태 변경 -->
                <td>
                    <a class="btn btn-primary" href="{% url 'todos:update' todo.pk %}">변경</a>
                </td>
                <!-- 삭제 -->
                <td>
                    <a href="{% url 'todos:delete' todo.pk %}" class="btn btn-danger">삭제</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}